[package]
name = "ceksiak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.12.4", features = [
    "cookies",
    "rustls-tls",
    "multipart",
] }
scraper = "0.19.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serenity = "0.12.2"
tokio = { version = "1.38.0", features = ["full"] }
